package life.haid.community.community01.mapper;

import java.util.List;
import life.haid.community.community01.model.User;
import life.haid.community.community01.model.UserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_1
     *
     * @mbg.generated Wed Feb 26 20:27:49 GMT+08:00 2020
     */
    int updateByPrimaryKey(User record);
}